apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-api-service
  labels:
    app: k8s-demo-api-service
spec:
  selector:
    app: k8s-demo-api
  ports:
    - protocol: TCP
      port: 3000 # Service port, what CLIENT/Other Pods will access
      targetPort: 3000 # Container port, internal comm of PODS (containers)
  type: NodePort